name: python exercise

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout del proyecto
        uses: actions/checkout@v4

      - name: configurar python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecucion de pruebas
        run: pytest test_main.py
        
      - name: Compilacion exitosa
        run: echo "Compilacion exitosa"
